language: node_js
node_js:
  - 8
before_install:
  - npm config set depth 0
script:
  - npm run lint
  - npm run test
  - npm run build
  - nyc --silent npm run test
  - nyc report --reporter=text-lcov | coveralls
after_success:
  - npm run build
  - semantic-release pre
  - npm publish
  - semantic-release post
notifications:
  email: false
sudo: false
